# Scroll nicely in the terminal
# The two first are omarchy defaults
windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2
windowrule = match:class org.wezfurlong.wezterm, scroll_touchpad 0.4

# Steam
windowrule = tile 1, match:title Steam

# Steam games
windowrule = monitor 1, match:class steam_app_\d+
windowrule = fullscreen 1, match:class steam_app_\d+
windowrule = opacity 1, match:class steam_app_\d+

# Exception for ubisoft connect popup
windowrule = fullscreen 0, match:class steam_app_2225070

# Mcsr
windowrule = monitor 1, match:title Minecraft\*\s1\.16\.1\s-\sMCSR\sRanked
windowrule = no_anim 1, match:title Minecraft\*\s1\.16\.1\s-\sMCSR\sRanked
windowrule = opacity 1, match:title Minecraft\*\s1\.16\.1\s-\sMCSR\sRanked

windowrule = monitor 0, match:class ninjabrainbot-Main 
windowrule = float 1, match:class ninjabrainbot-Main 
windowrule = opacity 1, match:class ninjabrainbot-Main 

windowrule = tile 1, match:initial_title OBS\s32.1.0\s-\sProfile:\sUntitled\s-\sScenes:\sUntitled
windowrule = monitor 0, match:initial_title OBS\s32.1.0\s-\sProfile:\sUntitled\s-\sScenes:\sUntitled
