# For this to activate. Run keyd-application-mapper. I have it in autostart
# [*|*mcsr*]
[*|*ranked*]

# ── Misc ────────────────────────────────────────────────────────────────────
mouse1 = backspace
h = 0
z = f3 # can't really bound two keys to f3, illegal
mouse2 = f3

# ── Search Crafting remaps ───────────────────────────────────────────────────
# Repositions your left hand to type item names in the crafting search box.

# Trying new layout to avoid f3 + a or d
# Only search craft stuff I use now:
# be -> bow, aw, ke
# ro
#
# be -> ew
e = b
w = e
# (b)ow -> ds
d = o
s = w
# aw -> fs
f = a
# ke -> qw
q = k
# ro -> rd

# to avoid f3 + a
a = j

x = f

b = l
