customCommands:
  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"

os:
  # I usually use lazygit embedded in nvim. For this, I use
  # https://github.com/willothy/flatten.nvim to simplify the setup without the
  # need for external applications.
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"

promptToReturnFromSubprocess: false
